### ISSUE TITLE
issue with siepic y_branch port naming

### ISSUE THREAD

**Issue by BeamAudio** [BYUCamachoLab/simphony#110]
hi, i'm trying to build a basic Mach-Zehnder in colab and I get the error that port_1 doesn't exist. it is being caused by the parser, as i can write "port 1" in the circuit description, but once executing that cell, it throws the error.

**Comment by sequoiap** [comment]
Thanks for your bug report. I've looked into it, and it is caused by a change in sax that requires all port names to be valid identifiers. I've modified the port names in the models provided by simphony to replace spaces with underscores (i.e. ``port 1`` -> ``port_1``). This has been implemented in commit 3653bb5 and released to PyPI as 0.7.2.
